//loaders
import {exp} from 'react-native-reanimated';

export const LOGIN_ENABLE_LOADER = 'LOGIN_ENABLE_LOADER';
export const LOGIN_DISABLE_LOADER = 'LOGIN_DISABLE_LOADER';

//theming
export const TOGGLE_THEME = 'TOGGLE_THEME';

// login
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_RESPONSE = 'LOGIN_RESPONSE';
export const LOGIN_FAILED = 'LOGIN_FAILED';

export const SIGNUP_REQUEST = 'SIGNUP_REQUEST';
export const SIGNUP_RESPONSE = 'SIGNUP_RESPONSE';
export const SIGNUP_FAILED = 'SIGNUP_FAILED';

export const FORGOT_PASSWORD_REQUEST = 'FORGOT_PASSWORD_REQUEST';
export const FORGOT_PASSWORD_RESPONSE = 'FORGOT_PASSWORD_RESPONSE';
export const FORGOT_PASSWORD_FAILED = 'FORGOT_PASSWORD_FAILED';

export const VERIFY_OTP_REQUEST = 'VERIFY_OTP_REQUEST';
export const VERIFY_OTP_RESPONSE = 'VERIFY_OTP_RESPONSE';
export const VERIFY_OTP_FAILED = 'VERIFY_OTP_FAILED';

export const UPDATE_PASSWORD_REQUEST = 'UPDATE_PASSWORD_REQUEST';
export const UPDATE_PASSWORD_RESPONSE = 'UPDATE_PASSWORD_RESPONSE';
export const UPDATE_PASSWORD_FAILED = 'UPDATE_PASSWORD_FAILED';


export const GET_FABRIC_REQUEST = 'GET_FABRIC_REQUEST';
export const FABRIC_SUCCESS = 'FABRIC_SUCCESS';
export const FABRIC_FAILURE = 'FABRIC_FAILURE';

export const GET_CATALOG_REQUEST = 'GET_CATALOG_REQUEST';
export const CATALOG_SUCCESS = 'CATALOG_SUCCESS';
export const CATALOG_FAILURE = 'CATALOG_FAILURE';

export const GET_PRODUCT_REQUEST = 'GET_PRODUCT_REQUEST';
export const PRODUCT_SUCCESS = 'PRODUCT_SUCCESS';
export const PRODUCT_FAILURE = 'PRODUCT_FAILURE';

export const STORE_CART_DATA = 'STORE_CART_DATA';
export const CLEAR_CART = 'CLEAR_CART';


export const ADD_ADDRESS_REQUEST = 'ADD_ADDRESS_REQUEST';
export const ADD_ADDRESS_RESPONSE = 'ADD_ADDRESS_RESPONSE';
export const ADD_ADDRESS_FAILED = 'ADD_ADDRESS_FAILED';

export const UPDATE_ADDRESS_REQUEST = 'UPDATE_ADDRESS_REQUEST';
export const UPDATE_ADDRESS_RESPONSE = 'UPDATE_ADDRESS_RESPONSE';
export const UPDATE_ADDRESS_FAILED = 'UPDATE_ADDRESS_FAILED';


export const FETCH_ADDRESS_REQUEST = 'FETCH_ADDRESS_REQUEST';
export const FETCH_ADDRESS_RESPONSE = 'FETCH_ADDRESS_RESPONSE';
export const FETCH_ADDRESS_FAILED = 'FETCH_ADDRESS_FAILED';

export const ADMIN_MY_ORDERS_REQUEST = 'ADMIN_MY_ORDERS_REQUEST';
export const ADMIN_MY_ORDERS_RESPONSE = 'ADMIN_MY_ORDERS_RESPONSE';
export const ADMIN_MY_ORDERS_FAILED = 'ADMIN_MY_ORDERS_FAILED';


export const ADMIN_CUSTOMERS_REQUEST = 'ADMIN_CUSTOMERS_REQUEST';
export const ADMIN_CUSTOMERS_RESPONSE = 'ADMIN_CUSTOMERS_RESPONSE';
export const ADMIN_CUSTOMERS_FAILED = 'ADMIN_CUSTOMERS_FAILED';

export const CUSTOMERS_REPORTS_REQUEST = 'CUSTOMERS_REPORTS_REQUEST';
export const CUSTOMERS_REPORTS_RESPONSE = 'CUSTOMERS_REPORTS_RESPONSE';
export const CUSTOMERS_REPORTS_FAILED = 'CUSTOMERS_REPORTS_FAILED';

export const PRODUCTS_REPORTS_REQUEST = 'PRODUCTS_REPORTS_REQUEST';
export const PRODUCTS_REPORTS_RESPONSE = 'PRODUCTS_REPORTS_RESPONSE';
export const PRODUCTS_REPORTS_FAILED = 'PRODUCTS_REPORTS_FAILED';


export const ODD_REPORTS_REQUEST = 'ODD_REPORTS_REQUEST';
export const ODD_REPORTS_RESPONSE = 'ODD_REPORTS_RESPONSE';
export const ODD_REPORTS_FAILED = 'ODD_REPORTS_FAILED';


export const DISPATCH_ORDER_REPORTS_REQUEST = 'DISPATCH_ORDER_REPORTS_REQUEST';
export const DISPATCH_ORDER_REPORTS_RESPONSE = 'DISPATCH_ORDER_REPORTS_RESPONSE';
export const DISPATCH_ORDER_REPORTS_FAILED = 'DISPATCH_ORDER_REPORTS_FAILED';


export const DEVICE_LOGS_REQUEST = 'DEVICE_LOGS_REQUEST';
export const DEVICE_LOGS_RESPONSE = 'DEVICE_LOGS_RESPONSE';
export const DEVICE_LOGS_FAILED = 'DEVICE_LOGS_FAILED';

export const FEEDBACK_REQUEST = 'FEEDBACK_REQUEST';
export const FEEDBACK_RESPONSE = 'FEEDBACK_RESPONSE';
export const FEEDBACK_FAILED = 'FEEDBACK_FAILED';


export const ORDER_DETAIL_REQUEST = 'ORDER_DETAIL_REQUEST';
export const ORDER_DETAIL_RESPONSE = 'ORDER_DETAIL_RESPONSE';
export const ORDER_DETAIL_FAILED = 'ORDER_DETAIL_FAILED';

export const ORDER_ACCEPT_REQUEST = 'ORDER_ACCEPT_REQUEST';
export const ORDER_ACCEPT_RESPONSE = 'ORDER_ACCEPT_RESPONSE';
export const ORDER_ACCEPT_FAILED = 'ORDER_ACCEPT_FAILED';

export const ORDER_REJECT_REQUEST = 'ORDER_REJECT_REQUEST';
export const ORDER_REJECT_RESPONSE = 'ORDER_REJECT_RESPONSE';
export const ORDER_REJECT_FAILED = 'ORDER_REJECT_FAILED';

export const ORDER_PLACED_REQUEST = 'ORDER_PLACED_REQUEST';
export const ORDER_PLACED_RESPONSE = 'ORDER_PLACED_RESPONSE';
export const ORDER_PLACED_FAILED = 'ORDER_PLACED_FAILED';

export const GET_USER_DETAILS_REQUEST = 'GET_USER_DETAILS_REQUEST';
export const GET_USER_DETAILS_RESPONSE = 'GET_USER_DETAILS_RESPONSE';
export const GET_USER_DETAILS_FAILED = 'GET_USER_DETAILS_FAILED';

export const UPDATE_USER_DETAILS_REQUEST = 'UPDATE_USER_DETAILS_REQUEST';
export const UPDATE_USER_DETAILS_RESPONSE = 'UPDATE_USER_DETAILS_RESPONSE';
export const UPDATE_USER_DETAILS_FAILED = 'UPDATE_USER_DETAILS_FAILED';

export const MODIFY_ORDER = 'modify_order';

export const LOG_OUT = 'LOG_OUT';

export const GET_STATE_LIST = 'GET_STATE_LIST'
export const GET_STATE_LIST_SUCCESS = 'GET_STATE_LIST_SUCCESS'
export const GET_STATE_LIST_FAILED = 'GET_STATE_LIST_FAILED'

export const GET_CITY_LIST = 'GET_CITY_LIST'
export const GET_CITY_LIST_SUCCESS = 'GET_CITY_LIST_SUCCESS'
export const GET_CITY_LIST_FAILED = 'GET_CITY_LIST_FAILED'

export const GET_STATE_WISE_CITIES ='GET_STATE_WISE_CITIES'
export const GET_STATE_WISE_CITIES_SUCCESS ='GET_STATE_WISE_CITIES_SUCCESS'
export const GET_STATE_WISE_CITIES_FAILED ='GET_STATE_WISE_CITIES_FAILED'

export const SEND_OTP = 'SEND_OTP'
export const SEND_OTP_SUCCESS = 'SEND_OTP_SUCCESS'
export const SEND_OTP_FAILED = 'SEND_OTP_FAILED'

export const REJECT_ORDER='REJECT_ORDER'
export const REJECT_ORDER_SUCCESS='REJECT_ORDER_SUCCESS'
export const REJECT_ORDER_FAILED='REJECT_ORDER_FAILED'